apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo
  description: An example deployment of a Backstage application.
  annotations:
    github.com/project-slug: backstage/demo
    jenkins.io/job-full-name: backstage
spec:
  type: website
  owner: backstage/maintainers
  lifecycle: experimental
